#!/usr/bin/env python
import os, sys
import signal
from options import options
from chorus_installer import ChorusInstaller, failover, upgrade
from chorus_executor import PSQLException
from log import logger

def exit_gracefully(signum, frame):
    print "\nSetup aborted, Cancelled by user"
    logger.info("cleaning up setup...")
    failover()
    sys.exit(1)
try:
    signal.signal(signal.SIGINT, exit_gracefully)
    installer = ChorusInstaller()
    installer.setup()
    print "Completely Setup"
    if upgrade:
        print "Confirm custom configuration settings as directed in the upgrade guide before restarting Chorus."
    print "*To start Chorus, run the following commands:"
    print "*source %s/chorus_path.sh" % options.chorus_path
    print "*chorus_control.sh start"
except Exception as e:
    logger.error("Exception Occured, see install.log for details")
    logger.debug(e)
    logger.info("cleaning up setup...")
    failover()

