#!/usr/bin/env python
import os
from installer_io import InstallerIO
io = InstallerIO()

def run(self, command):
    p = subprocess.Popen(command, shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    stdout, stderr = p.communicate()
    if stdout:
        print stdout
    if stderr:
        print stderr

    return p.returncode, stdout, stderr

def install():
    user = io.prompt("which user do you want to use to install chorus[default: chorus]", default="chorus")
    run("useradd chorus")
    chorus_path = io.prompt("Please enter the full path to the Chorus installation directory[default: /usr/local/chorus]", default="/usr/local/chorus")
    data_path = io.prompt("Please enter the full path to the Chorus data directory (recommended 500GB)[default:/data/chorus]", default="/data/chorus")

    run("mkdir -p %s" % chorus_path)
    run("mkdir -p %s" % data_path)
    installation_path = os.path.join(os.path.dirname(__file__), ".")
    version = ""
    with open(os.path.join(installation_path, "version_build"), "r") as f:
        version = f.read().strip()

    run("cp -rf %s %s" % (os.path.join(installation_path, "version_build"), chorus_path))
    release_path = os.path.join(chorus_path, "releases/%s" % version)
    run("cp -rf %s %s" % (installation_path, release_path))
    run("chown -R %s" % chorus_path)
    run("chown -R %s" % data_path)
    run("su - %s -c \"packaging/setup/chorus_server setup --chorus_path=%s --data_path=%s\"" % (user, chorus_path, data_path))

try:
    install()
except Exception as e:
    print e
