#!/usr/bin/env python
import os
import sys
import subprocess
import shlex
import signal
import shutil
import pwd
from setup import color
from setup import installer_io
from setup import func_executor
bold = color.bold
processify = func_executor.processify


silent = False
if len(sys.argv) == 2 and sys.argv[1]=="-s":
    silent = True
io = installer_io.InstallerIO(silent)

def exit_gracefully(signum, frame):
    print "\nInstall aborted, Cancelled by user"
    sys.exit(1)

def _eula_by_brand():
    filename = ""
    if os.getenv('PIVOTALLABEL') is None:
        filename = 'eula_alpine.txt'
    else:
        filename = 'eula_emc.txt'
    filename = os.path.join(os.path.dirname(os.path.abspath(__file__)), "setup/" + filename)
    with open(filename, 'r') as f:
        eula = f.read();
    return eula

def prompt_for_eula():
    eula = _eula_by_brand()
    print eula
    ret = io.require_confirmation("Do you accept the terms above?")
    if not ret:
        return False
    return True

def run(command):
    p = subprocess.Popen(command, shell=True, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    stdout, stderr = p.communicate()
    return p.returncode, stdout, stderr

def run_interact(command, user):
    def demote(user_uid, user_gid):
        os.setgid(user_gid)
        os.setuid(user_uid)
    pw_record = pwd.getpwnam(user)
    user_uid = pw_record.pw_uid
    user_gid = pw_record.pw_gid
    return subprocess.call(shlex.split(command), preexec_fn=demote(user_uid, user_gid))


def output(msg):
    print "INFO : " + bold(msg)

def detect_pre_version(chorus_path):
    current_path = os.path.join(chorus_path, "current")
    if os.path.lexists(current_path) and os.path.islink(current_path):
        pre_version = os.path.basename(os.path.realpath(current_path))
        pre_version = pre_version.split("-")[0]
        return pre_version
    return None
def compare_version(cur, pre):
    cur = int(cur.replace(".", ""))
    pre = int(pre.replace(".", ""))
    if cur == pre:
        return 0
    elif cur < pre:
        return -1
    else:
        return 1

@processify(msg="->Copying Production...")
def copy_to_dest(installation_path, chorus_path, data_path, release_path):
    ret, stdout, stderr = run("mkdir -p %s && mkdir -p %s" % (chorus_path, data_path))
    if ret != 0:
        raise Exception("[ERROR] " + stderr)

    ret, stdout, stderr = run("cp -rf %s %s" % (os.path.join(installation_path, "version_build"), chorus_path))
    if ret != 0:
        raise Exception("[ERROR] " + stderr)
    if os.path.exists(release_path):
        shutil.rmtree(release_path)
    ret, stdout, stderr = run("mkdir -p %s && cp -rf %s %s" % (release_path, installation_path, release_path))
    if ret != 0:
        raise Exception("[ERROR] " + stderr)

@processify(msg="->Granting permission...")
def grant_permission(user, chorus_path, data_path):
    ret, stdout, stderr = run("chown -R %s:%s %s && chown -R %s:%s %s" % (user, user, chorus_path, user, user, data_path))
    if ret != 0:
        raise Exception("[ERROR] " + stderr)

def install():
    if not prompt_for_eula():
        print "Install aborted, Cancelled by user"
        return
    user = io.prompt("which user do you want to use to install chorus[default: chorus]", default="chorus")
    ret, stdout, stderr = run("useradd chorus")
    if ret not in [0,9]:
        if ret == 126:
            stderr += "Please run as the user with root permission\n"
        raise Exception("[ERROR] " + stderr)
    chorus_path = io.prompt("Please enter the full path to the Chorus installation directory[default: /usr/local/chorus]", default="/usr/local/chorus")
    data_path = io.prompt("Please enter the full path to the Chorus data directory (recommended 500GB)[default:/data/chorus]", default="/data/chorus")
    installation_path = os.path.join(os.path.dirname(__file__), "..")

    version = ""
    with open(os.path.join(installation_path, "version_build"), "r") as f:
        version = f.read().strip()

    release_path = os.path.join(chorus_path, "releases/%s" % version)

    pre_version = detect_pre_version(chorus_path)
    cur_version = version.split("-")[0]
    msg = "Installing"
    if pre_version is not None and not compare_version(cur_version, pre_version) == 0:
        default = "yes"
        if compare_version(cur_version, pre_version) == 1:
            msg = "Upgrade"
        else:
            default = "no"
            msg = "Downgrade"
        if not io.require_confirmation("You already have chorus version: %s installed. \n" % pre_version\
			+"Do you want to %s the chorus to version: %s:" % (msg, cur_version), default):
            print "%s aborted, Cancelled by user" % msg
            return

    output("%s chorus version: %s to chorus and data path:" % (msg, version))
    copy_to_dest(installation_path, chorus_path, data_path, release_path)

    output("change %s's owner to %s:" % (chorus_path, user))
    grant_permission(user, chorus_path, data_path)

    _s = ""
    if silent:
        _s = "-s"
    run_interact("%s setup %s --chorus_path=%s --data_path=%s" % \
                 (os.path.join(release_path, "packaging/setup/chorus_server"), _s, chorus_path, data_path), user)

try:
    signal.signal(signal.SIGINT, exit_gracefully)
    install()
except Exception as e:
    print e
